Add r session images
rstudio/rstudio-docker-products pull request #138
Opened 2021-06-14 13:59 UTC by colearendt

2021-06-22 19:21 UTC, MariaSemple requested changes

2021-06-22 19:21 UTC, MariaSemple commented on r-session-complete/NEWS.md
> +code-server is at `/opt/code-server/code-server`
`/opt/code-server/code-server` is deprecated and will be removed in newer versions, but the bin path is there on older versions.

```suggestion
code-server is at `/opt/code-server/bin/code-server`
```

2021-06-22 19:47 UTC, bdeitte commented on .github/workflows/build-latest.yaml
> +          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}latest
Can you explain what all of these changes do?  I didn't follow all of it from one read through at least.  And is this anything that @nahara7 needs to know about with her upcoming testing work?

2021-06-22 19:49 UTC, bdeitte commented on r-session-complete/README.md
> +Launcher, and Kubernetes.
When this is merged in I would recommend we change all of the docker-r-session-complete repo README to say the repo is deprecated and point here, to reduce confusion.

2021-06-22 19:51 UTC, bdeitte commented on r-session-complete/README.md
> +Launcher, and Kubernetes.
Also are you solving the DockerHub README issue as part of this work?  DockerHub takes the root README always, right?

2021-06-22 20:31 UTC, colearendt commented on .github/workflows/build-latest.yaml
> +          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}latest
This is a no-op for all of the existing images, because `tag_prefix` resolves to nothing. For the `r-session-complete` images, we specify `tag_prefix=bionic-` or `tag_prefix=centos7-`so that the images will become `bionic-latest` and `centos7-latest`, for instance, because the r-session-complete images have two OS's.

This is mostly done for backwards compatibility with the existing setup. It shouldn't affect her testing at all 😄

2021-06-22 20:33 UTC, colearendt commented on r-session-complete/README.md
> +Launcher, and Kubernetes.
Yes, definitely will update the docker-r-session-complete repo to point here. 

As for the DockerHub README, the current doc improvement plan is:
- update / decouple the docs here in the repo
- copy those to DockerHub

There are ways to automate this with GHA, but it's not immediately clear how well they will work with our setup. Planning to take a couple of cycles improving the docs once the meat and potatoes have landed 😄

2021-06-22 23:41 UTC, bdeitte commented on r-session-complete/README.md
> +Launcher, and Kubernetes.
Makes sense, sounds like a good plan!

2021-06-23 10:50 UTC, colearendt commented
@MariaSemple It looks like all of the `/opt/code-server/code-server` references were in the NEWS. I added a new NEWS entry for 1.4.1717-3 to update, but I think it's ok to leave the history in the NEWS file for reference.

2021-06-23 16:07 UTC, MariaSemple commented
Ah, I thought I saw a reference in vscode.conf.

2021-06-23 20:38 UTC, merged