Function Service Testing
rstudio/rstudio-docker-products pull request #164
Opened 2021-07-19 17:41 UTC by nahara7

### Intent
To provide Goss tests for Connect, Package Manager, and Workbench to ensure they are running and that their configuration files (`rstudio-connect.gcfg`, `rstudio-pm.gcfg`, `rserver.conf`) are of the correct format

Addresses #155 

### Approach
Start up service in the beginning of each corresponding `run_tests.sh` and write it's output to a temporary `startup.log` file added in the dockerfile. 
1. Additional Goss  test to see if the process is running 
2. Additional Goss test to check that the `startup.log` file contains no errors trying to read the process's configuration file.

2021-07-20 13:38 UTC, colearendt requested changes
Looking awesome!! A couple of feedback items that apply to all of the different products 😄 I didn't go through and tag each instance of it - thought that might get a little busy 🙈

2021-07-20 13:38 UTC, colearendt commented on Makefile
> -	docker rm rstudio-connect
@bdeitte added these (and discussed their reasoning) here: https://github.com/rstudio/rstudio-docker-products/pull/112

Generally speaking, it's good to proceed with caution modifying too many things (even if you think they are unnecessary) in one go, since it can provide friction for reviewers to review the change that you care more about. In more formal projects especially, you want to ensure that the only changes you make are related to the issue you are working on, and create a separate issue if you want to discuss / get buy in on tangential / other related changes.

(That said, if you need such changes to get your dev work working smoothly, this is something that I have done before - modifying locally and just not committing the changes since they are personal preferences. And if that gets frustrating "enough," then its probably worth opening an issue to discuss improvements 😄 )

2021-07-20 13:38 UTC, colearendt commented on connect/Dockerfile
> +     touch /tmp/startup.log
Is there a reason for the touch statements? I think we can remove these `touch` statements for a few reasons:
1. these logs are used only in testing / are not essential to the proper functioning of the service, so they should not be baked into the images
2. the reason we had the "touch" pattern before was so that our `tail -f` commands could find them. In general practice, touching files is definitely something to avoid unless there is a particular reason for doing so 😄

2021-07-20 13:38 UTC, colearendt commented on connect/startup.sh
> +# let this be inherited by child processes
```suggestion
# ensure these cannot be inherited by child processes
```

`lest` was actually intentional. Me and my nerdy [old english](https://www.merriam-webster.com/dictionary/lest) 😅

2021-07-20 13:38 UTC, colearendt commented on connect/test/run_tests.sh
> +/opt/rstudio-connect/bin/connect --config /etc/rstudio-connect/rstudio-connect.gcfg 2>/tmp/startup.log
Let's start Connect the same way the container does `tini -- /usr/local/bin/startup.sh`. That should handle licensing better too.

2021-07-20 13:38 UTC, colearendt commented on connect/test/run_tests.sh
> +
Drop unnecessary whitespace, please! 😄 VSCode may have a way to do this automatically.

2021-07-20 13:47 UTC, colearendt commented on connect/test/run_tests.sh
> +/opt/rstudio-connect/bin/connect --config /etc/rstudio-connect/rstudio-connect.gcfg 2>/tmp/startup.log
Also, I think you need to background these processes, or they will block the execution of the rest of the service.

2021-07-20 14:24 UTC, nahara7 commented on connect/Dockerfile
> +     touch /tmp/startup.log
Okay ! I had originally mounted them as temporary files. Would you suggest going back to that ?

2021-07-21 15:34 UTC, colearendt reviewed
This is looking really good! Just a couple of items / ideas (which apply to all 3 places)

2021-07-21 15:34 UTC, colearendt commented on connect/test/run_tests.sh
> +cat > /tmp/startup.log
Is this necessary? 😮

2021-07-21 15:34 UTC, colearendt commented on connect/test/run_tests.sh
> +tini -- /usr/local/bin/startup.sh 2>/tmp/startup.log &
```suggestion
tini -- /usr/local/bin/startup.sh > /tmp/startup.log 2>&1 &
```

Otherwise `stdout` will still go to the terminal 😄

2021-07-21 15:34 UTC, colearendt commented on server-pro/docker-compose.test.yml
> +      - RSW_LICENSE
This RSW_LICENSE will not _actually_ work until we switch RSP to RSW. Should we switch back to RSP for now, and take the RSW bit as a part of follow-up? Alternatively, we might could do something like this to fill the gap:

```suggestion
      - RSP_LICENSE=${RSW_LICENSE}
```

2021-07-21 17:40 UTC, nahara7 commented on connect/test/run_tests.sh
> +cat > /tmp/startup.log
Is there another way you think we should create the log file ?

2021-07-21 18:20 UTC, colearendt commented on connect/test/run_tests.sh
> +cat > /tmp/startup.log
It should be created automatically by the lines below 😄 We only have to create the log file _before starting the process_ if we need to `tail` the file. Hopefully we are moving away from that need across the board 😄

2021-07-22 16:16 UTC, nahara7 commented on connect/test/run_tests.sh
> +cat > /tmp/startup.log
I see !

2021-07-23 19:09 UTC, colearendt reviewed
Looking awesome! Just a few little nits and then we should be good to go!! Well done!

2021-07-23 19:09 UTC, colearendt commented on connect/startup.sh
> +    /opt/rstudio-connect/bin/license-manager deactivate >/dev/null 2>&1 &
Why is this backgrounded?

2021-07-23 19:09 UTC, colearendt commented on server-pro/test/run_tests.sh
> +
Missing a trailing newline here

2021-07-23 19:09 UTC, colearendt commented on workbench/conf/launcher.pem
> +-----BEGIN PRIVATE KEY-----
We definitely don't want these files committed 😄 Also, we should probably add them to .gitignore if they aren't already?

2021-07-30 10:30 UTC, colearendt approved these changes
One last little round of tweaks, and then I think we are good to go!! Well done!

2021-07-30 10:30 UTC, colearendt commented on connect/test/run_tests.sh
> +tini -- /usr/local/bin/startup.sh 2>/tmp/startup.log 2>&1 &
```suggestion
tini -- /usr/local/bin/startup.sh >/tmp/startup.log 2>&1 &
```

2021-07-30 10:30 UTC, colearendt commented on package-manager/test/run_tests.sh
> +tini -- /usr/local/bin/startup.sh 2>/tmp/startup.log 2>&1 &
```suggestion
tini -- /usr/local/bin/startup.sh >/tmp/startup.log 2>&1 &
```

2021-07-30 10:30 UTC, colearendt commented on server-pro/test/run_tests.sh
> +rstudio-server start 2>/tmp/startup.log 2>&1 &
```suggestion
tini -- /usr/local/bin/startup.sh >/tmp/startup.log 2>&1 &
```

2021-07-30 10:31 UTC, colearendt commented on connect/test/run_tests.sh
> +tini -- /usr/local/bin/startup.sh 2>/tmp/startup.log 2>&1 &
`2>` says that `stderr` should go to this file. Then `2>&1` says `stderr` should go to the place where `stdout` went.

Instead, we want: `stdout` goes to file, and `stderr` goes to where `stdout` went ( so everything goes to the file ) 😄

2021-07-30 10:41 UTC, colearendt commented
Also, don't worry about the CI failures. Those are failing on main too - the preview builds have changed how they are notated, so as long as it is preview Workbench / the r-session-complete, failure is expected ATM

2021-08-03 01:09 UTC, colearendt commented on server-pro/test/run_tests.sh
> +rstudio-server start >/tmp/startup.log 2>&1 &
Why did you go back to this one? If we invoke with `tini -- /usr/local/bin/startup.sh`, we behave like the image does 😄

2021-08-03 01:30 UTC, nahara7 commented on server-pro/test/run_tests.sh
> +rstudio-server start >/tmp/startup.log 2>&1 &
I was about to ask you ! I was just testing because I noticed the `pgrep rserver` test fails when we startup with `tini -- /usr/local/bin/startup.sh` but it works when using `rstudio-server start`. Do you have any insights on why ?

2021-08-04 02:41 UTC, colearendt commented on server-pro/test/run_tests.sh
> +rstudio-server start >/tmp/startup.log 2>&1 &
Woops - sorry for the late reply here. I am suspicious that something in the product is failing. Licensing issue or otherwise. If you are doing this interactively (there are docs on how to do that here: https://github.com/rstudio/rstudio-docker-products/blob/main/RELEASE.md#testing-locally - I have not used these in a while, so hopefully they still work!), then take a look at `/tmp/startup.log` to see what the problem is, maybe?

2021-08-12 20:43 UTC, merged