Additional R / Python content images
rstudio/rstudio-docker-products pull request #234
Opened 2021-11-16 21:24 UTC by sagerb

Adding additional content pro images to supply these combinations of R and Python:

- R:4.0.5, Python:3.7.10
- R:4.0.5, Python:3.6.13
- R:3.6.3, Python:3.6.13
- R:3.6.3, Python:2.7.18
- R:3.5.3, Python:2.7.18
- R:3.4.4, Python:3.7.10
- R:3.3.3, Python:3.6.13

closes rstudio/connect#20123

Initial verification will be done w/ successful CI.

2021-11-16 21:31 UTC, aronatkins approved these changes

2021-11-16 21:31 UTC, aronatkins commented on content/matrix.json
> +  {"r": "4.1.0", "py": "3.9.2", "drivers": "1.8.0", "os": "bionic"},
nit: the existing entries were sorted (R version as primary sort); could we do the same?

2021-11-17 14:32 UTC, aronatkins commented on connect/NEWS.md
> +# 2021.11.0
@colearendt - should we retain the 2021.10.0 version since 2021.11.0 is not yet public?

2021-11-17 14:33 UTC, aronatkins reviewed
Waiting for feedback from @colearendt before approval / merge

2021-11-17 16:25 UTC, colearendt commented on connect/NEWS.md
> +- Add additional content images.
I wouldn't put it here since it's not related to the connect image. My opinion would be either a `NEWS.md` in the `content` directory, or else we don't bother 🤷‍♂️  😅

2021-11-17 16:27 UTC, colearendt commented on connect/NEWS.md
> +# 2021.11.0
Yeah, I agree. The general idea is to keep a list of what "image" changes happened when. I think it's probably worth pulling this out of the NEWS.md for connect, and can just update the README.md. If we decide to maintain a NEWS.md for the content images, we can always just use date `# 2021-11-17`, etc. since there is no such thing as a "version" 😄

2021-11-17 19:02 UTC, sagerb commented on connect/NEWS.md
> +- Add additional content images.
Changes made.

2021-11-17 19:02 UTC, sagerb commented on connect/NEWS.md
> +# 2021.11.0
changes made.

2021-11-17 19:03 UTC, aronatkins approved these changes

2021-11-17 20:42 UTC, colearendt approved these changes
LGTM!

2021-11-17 20:43 UTC, colearendt requested changes
Actually - take that back. Let's look at the build failures

2021-11-17 20:44 UTC, colearendt approved these changes
Nvm. The "pro" images fail to build in their first PR because they depend on pushed "base" images 😢  That is an unfortunate case

2021-11-17 20:53 UTC, merged