Bump connect to 2021.12.0
rstudio/rstudio-docker-products pull request #248
Opened 2021-12-13 18:56 UTC by scottmmjackson

- Bump connect version to 2021.12.0

2021-12-13 18:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=248) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rstudio-docker-products?pullRequest=248) it.</sub>

2021-12-13 19:02 UTC, aronatkins requested changes

2021-12-13 19:02 UTC, aronatkins commented on connect/Dockerfile
> +ARG RSC_VERSION=2021.12.0
There are additional references. As found by `git grep`:

```
Makefile:8:RSC_VERSION ?= 2021.11.1
connect-content-init/Dockerfile:12:ARG RSC_VERSION=2021.11.1
connect/.env:1:RSC_VERSION=2021.11.1
connect/Dockerfile:103:ARG RSC_VERSION=2021.11.1
docker-compose.yml:27:        RSC_VERSION: 2021.11.1
docker-compose.yml:28:    image: rstudio/rstudio-connect:2021.11.1
```

2021-12-13 20:08 UTC, colearendt commented
Docs on an easy way to update: https://github.com/rstudio/rstudio-docker-products/blob/main/RELEASE.md#updating-product-versions

2021-12-16 15:15 UTC, scottmmjackson commented
@colearendt not sure that did what we wanted:

```
 M Makefile
 M connect-content-init/Dockerfile
 M connect/.env
 M docker-compose.yml
?? "connect-content-init/Dockerfile ''"
?? "connect/.env ''"
?? "connect/Dockerfile ''"
?? "docker-compose.yml ''"
?? "package-manager/.env ''"
?? "package-manager/Dockerfile ''"
?? "package-manager/rstudio-pm.gcfg ''"
?? "r-session-complete/bionic/.env ''"
?? "r-session-complete/bionic/Dockerfile ''"
?? "r-session-complete/centos7/.env ''"
?? "r-session-complete/centos7/Dockerfile ''"
?? "workbench/.env ''"
?? "workbench/Dockerfile ''"
```

2021-12-16 15:18 UTC, scottmmjackson commented
CLA assistant borked

can't agree to the CLA :(

2021-12-16 15:43 UTC, scottmmjackson commented
@aronatkins I think we're good for re-review here.

2021-12-16 16:33 UTC, colearendt commented
Weird! Sorry for the trouble - I'm curious why that failed - it always works well for me 😅 . @scottmmjackson are you on linux?

2021-12-16 16:33 UTC, merged

2021-12-16 16:45 UTC, scottmmjackson commented
@colearendt nope- mac OS here.

2021-12-16 18:51 UTC, colearendt commented
🤔  Very strange. I suspect we will need to do some more poking to see what the Makefile was doing there.