Refactor Workflows & Add Jammy Images
rstudio/rstudio-docker-products pull request #346
Opened 2022-07-12 17:06 UTC by dkasabovn

#### Intent

Previous workflows included logic within the yaml in order to tag and push various versions. I wanted to keep the steps between workflows the same while retaining log visibility.

#### Approach

Rather than a `Makefile` I have included a `Justfile` with one main command: `build`. Build takes in 4 arguments and then builds and tags images correctly based upon the arguments. This allows all of the logic that used to be in the workflow to migrate over to the `Justfile` making things easier to read and debug.

#### Automated Tests

Testing with ACT is not ideal.

#### Notes

Package manager - Jammy still doesn't work as it requires openssl 1.1 and the bionic build for daily is not working however, the latter is due to the specific version that is being built

Workflow Conditions - For the sake of testing they are currently only to run on pushes to my branch. And release doesn't push images. This will be fixed when things are ready to merge into main.

2022-07-12 17:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=346) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=346) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rstudio-docker-products?pullRequest=346) it.</sub>

2022-07-13 10:35 UTC, colearendt requested changes
Thanks! If you could say a bit more in your PR about context and choices, I think that would be super helpful. For instance:

- Why create the `docker/` subfolder? It feels redundant? Did you use this pattern from somewhere else? Is it preferable for some reason? 
- A note about things that are included but not actively in use (i.e. the Makefile changes, actions/single/action.yml), etc.
- Notes about any particularly complex problems you solved (can help reviewers pay more close attention there and understand your reasoning for certain choices)
- what is "ACT" testing?

Context helps a lot for someone not as close to the problem (me), especially when reviewing a sizable PR like this one 😄 

I still need to dig in a bit further and poke around at things!

2022-07-13 10:35 UTC, colearendt commented on .github/workflows/build-preview-v2.yaml
> +
Beware missing newline at the end of the file. Usually you can ensure this with a setting in your editor.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/23075542/178711061-7e9a15f3-3c3b-4ecb-bfd4-206e27fd0f80.png">

2022-07-13 10:35 UTC, colearendt commented on .github/workflows/build-preview-v2.yaml
> +          TAGS=`just b ${{ matrix.config.type }} ${{ matrix.config.package }} ${{ matrix.config.os }} ${{ steps.buildx.outputs.name }}`
I personally am more in favor of using the "full" names for the just targets (i.e. "build" instead of "b"). It's not a whole lot more writing, and it makes the command much more natural to read and understand (rather than having to go read the name of the step, etc.). 

The aliases are nice as a convenience interactively, but in code the more clear name should be worth the extra characters

2022-07-13 10:35 UTC, colearendt commented on Justfile
> +build-preview $TYPE $PRODUCT OS VERSION="" BRANCH=`git branch --show`:
This is pretty cool!

2022-07-13 10:35 UTC, colearendt commented on Justfile
> +    echo rstudio/rstudio-{{PRODUCT}}-preview:"${branch_prefix}"{{OS}}-"${safe_version}" \
Would you mind saying a bit in the PR or a comment about the variable syntax and why you ended up needing to go this direction?

2022-07-13 10:35 UTC, colearendt commented on Makefile
> +	docker build -t rstudio/rstudio-workbench:$(RSW_TAG_VERSION) --build-arg R_VERSION=$(R_VERSION) --build-arg RSW_VERSION=$(RSW_VERSION) workbench --file=./workbench/docker/bionic/Dockerfile
Were these the start of makefile changes that you ended up stopping progress on?

Would be good to have context - I would have expected other builds to go through a similar refactor

2022-07-13 10:35 UTC, colearendt commented on Justfile
> +    version=`just gv $PRODUCT --type=$TYPE --local`
Similar for the justfile - expounding that `gv` = `getversion` can make this read a lot clearer

2022-07-13 13:37 UTC, atheriel commented on .github/workflows/build-preview-v2.yaml
> +          TAGS=`just b ${{ matrix.config.type }} ${{ matrix.config.package }} ${{ matrix.config.os }} ${{ steps.buildx.outputs.name }}`
There are a few more instances of this below that could be fixed, too.

2022-07-13 13:40 UTC, atheriel commented on .github/workflows/build-preview-webhook-v2.yaml
> +        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
Since this is a webhook-based workflow, we should probably skip the branch check here and below.

2022-07-13 13:41 UTC, atheriel commented on .github/workflows/build-release-v2.yaml
> +        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
I think this is obviated by the branch filter above, and can be removed here and below.

2022-07-13 13:41 UTC, atheriel commented on .github/workflows/build-release-v2.yaml
> +      # - name: Push Images (just)
I'm not sure I understand why this is commented out here.

2022-07-13 13:42 UTC, atheriel commented on Justfile
> +alias b := build
As Cole mentioned above, these are fine for local development but I don't think aliases should be used in the CI workflows.

2022-07-13 13:48 UTC, atheriel commented
I'm a bit unclear as to why the workflow changes need to land alongside the new Jammy images -- is it possible to break these into separate PRs, or at least into separate commits?

2022-07-13 14:03 UTC, atheriel commented on package-manager/docker/jammy/Dockerfile
> +ARG RSPM_VERSION=2022.04.0-7
Does this RSPM release actually support Jammy? If not, maybe we should wait for the next one (which probably will) before adding this.

2022-07-13 14:04 UTC, atheriel commented on workbench/docker/jammy/Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
Nit: missing newline.

2022-07-13 14:04 UTC, atheriel commented on get-matrix.py
> +    print(json.dumps(matrix_conf))
Nit: missing newline.

2022-07-13 14:15 UTC, atheriel commented on Justfile
> +#!/usr/bin/env just --justfile
It would be nice if the `docker` command here was substitution-friendly so we could build with `nerdctl` or `podman`.

2022-07-13 16:15 UTC, dkasabovn commented on .github/workflows/build-preview-v2.yaml
> +      - name: Show Image Sizes
It was in the other workflows, so I just kept it.

2022-07-13 17:22 UTC, dkasabovn commented on .github/workflows/build-release-v2.yaml
> +        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
I'm pretty sure removing this `if` would push release on any pull request, let me know if this is intended.

2022-07-13 17:27 UTC, dkasabovn commented on Justfile
> +    echo rstudio/rstudio-{{PRODUCT}}-preview:"${branch_prefix}"{{OS}}-"${safe_version}" \
Added context, let me know if it is enough

2022-07-13 17:27 UTC, dkasabovn commented on Makefile
> +	docker build -t rstudio/rstudio-workbench:$(RSW_TAG_VERSION) --build-arg R_VERSION=$(R_VERSION) --build-arg RSW_VERSION=$(RSW_VERSION) workbench --file=./workbench/docker/bionic/Dockerfile
Added in description

2022-07-13 17:28 UTC, dkasabovn commented on .github/workflows/build-release-v2.yaml
> +      # - name: Push Images (just)
not wanting to push release versions before everything is approved

2022-07-13 17:31 UTC, dkasabovn commented on Justfile
> +#!/usr/bin/env just --justfile
Not sure what this means entirely. I've never built with podman or nerdctl, so if you could throw me an example, I can look for a way to integrate this into the build.

2022-07-13 17:32 UTC, dkasabovn commented on .github/workflows/build-preview-v2.yaml
> +          MATRIX=`just gm --types preview daily --os bionic jammy --packages workbench connect package-manager | jq -Mcr`
Will look into this in a bit

2022-07-13 17:33 UTC, dkasabovn commented on package-manager/docker/jammy/Dockerfile
> +ARG RSPM_VERSION=2022.04.0-7
No, but I figured it doesn't hurt to add this in for now. Let me know what you think.

2022-07-13 17:34 UTC, dkasabovn commented
> I'm a bit unclear as to why the workflow changes need to land alongside the new Jammy images -- is it possible to break these into separate PRs, or at least into separate commits?

Added context in pr header

2022-07-14 14:26 UTC, colearendt commented on .github/workflows/build-preview-v2.yaml
> +      - name: Show Image Sizes
Yeah, it was meant for debugging and an easy way to see how image size is affected by various PRs / etc. (before we push)

2022-07-14 14:37 UTC, atheriel commented on .github/workflows/build-release-v2.yaml
> +        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
Ah, you're right!

2022-07-15 13:11 UTC, bschwedler commented on connect/docker/jammy/Dockerfile
> +ARG R_VERSION=3.6.2
Is it possible to use to a more recent `R` Version like `4.1` or `4.2` since these are newly created images?

I don't have the context as to whether each of the products all support the newer R versions.


This would also apply to the other product images.

2022-07-15 16:54 UTC, dkasabovn commented on connect/docker/jammy/Dockerfile
> +ARG R_VERSION=3.6.2
I certaintly change that, but we'd have to make a decision image by image on this I believe

2022-07-20 18:08 UTC, closed without merging