Bump Package Manager to version 2022.07.0-9 and merge non-root changes
rstudio/rstudio-docker-products pull request #348
Opened 2022-07-20 13:07 UTC by tylfin

Merging in changes from dev-rspm and bumping image to `2022.07.0-9`

2022-07-20 14:40 UTC, atheriel commented
CI seems to be failing for a mysterious reason -- does the image seem to work correctly in your testing?

2022-07-20 15:13 UTC, tylfin commented
@atheriel Yup, we've been using the `dev-rspm` branch in our K8s cluster cc @rodrigobrim

2022-07-20 16:16 UTC, colearendt requested changes
I haven't tried this myself yet, but a handful of thoughts. One thing in particular:

For sizable changes like this, we should write up a thorough overview of changes in NEWS.md so users have a jumping off point of "where to dig further" if they are running, upgrading, or extending this image. Namely:

- run as user changes
- no longer need sandboxing / the privileged flag
- disabled metrics by default
- Changed DataDir from `/data` to `/var/lib/rstudio-pm`

2022-07-20 16:16 UTC, colearendt commented on package-manager/Dockerfile
> +LABEL maintainer="RStudio Package Manager Team <rspm@rstudio.com>"
Is this email address publicly routable? (some internal email addresses / groups are not). Moreover, not sure whether this is something y'all have standardized on handling for the other images? We have used `docker@rstudio.com` as an "IT oriented" place for inbound image notices

2022-07-20 16:16 UTC, colearendt commented on package-manager/README.md
> +1. The Package Manager image uses the `No Sandbox` option documented
Related to this, I suspect we should have an "upgrade notice" or something with the steps needed to upgrade to 2022.07, changing the default RunAs user, etc.

2022-07-20 16:16 UTC, colearendt commented on package-manager/README.md
> +`package-manager/rstudio-pm.gcfg`.
```suggestion
[`package-manager/rstudio-pm.gcfg`](./rstudio-pm.gcfg).
```

2022-07-20 16:21 UTC, colearendt commented
Oh, also - y'all missed updating the Makefile (which currently drives the CI build version): https://github.com/rstudio/rstudio-docker-products/blob/main/RELEASE.md

Worth noting that `make update-versions` fails on certain OS's... 😓 Hence #321

2022-07-20 16:30 UTC, colearendt commented
And re: CI, the container is failing to start on this:
```
2022/07/20 16:27:40 Creating pypi directory: /var/lib/rstudio-pm/pypi
2022/07/20 16:27:40 Creating launcher directory: /data/launcher_internal
2022/07/20 16:27:40 Error: Unable to initialize the configuration: mkdir /data: permission denied
```

From here in the config:
```
LauncherDir = /data/launcher_internal
```

2022-07-20 16:59 UTC, tylfin commented on package-manager/Dockerfile
> +LABEL maintainer="RStudio Package Manager Team <rspm@rstudio.com>"
```suggestion
LABEL maintainer="RStudio Docker <docker@rstudio.com>"
```

2022-07-20 16:59 UTC, tylfin commented on package-manager/README.md
> +1. The Package Manager image uses the `No Sandbox` option documented
Would this go in the [NEWS](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/NEWS.md) or elsewhere?

2022-07-20 20:22 UTC, glin commented on package-manager/rstudio-pm-float.gcfg
> +LauncherDir = /var/lib/rstudio-pm/launcher_internal
I made this change in the `dev-rspm` branch at https://github.com/rstudio/rstudio-docker-products/pull/340, so it should've been included already, hmm. Is this PR branch made off the latest `dev-rspm` changes? It would probably be better to use the same commit from https://github.com/rstudio/rstudio-docker-products/pull/340 to get the other changes from that PR and avoid conflicts between `main` and `dev-rspm`.

2022-07-20 21:08 UTC, colearendt commented on package-manager/README.md
> +1. The Package Manager image uses the `No Sandbox` option documented
NEWS at a minimum IMO. It also may be worth a note / pointer in the README? 🤷 Up to y'all!

2022-07-21 02:56 UTC, atheriel commented on package-manager/Dockerfile
> -EXPOSE 2112/tcp
I recall that Tyler had a reasonable answer in the original PR, we could dig it up.

2022-07-21 19:32 UTC, colearendt reviewed
Looking awesome! Just a few nits on wording 😄

2022-07-21 19:32 UTC, colearendt commented on package-manager/NEWS.md
> +- The `Server.DataDir` setting has been set back to default, for more information see the
Can we tell what these are explicitly and how to resolve? We know that it used to be `/data` and right now the default is `/var/lib/rstudio-pm`, right? I think that would be useful data. Something akin to:

To mirror old behavior, set
```
[Server]
DataDir = /data
```

It'd also be good to have a "BREAKING: " note in front of these bullets where a change is potentially breaking (helps admins see quickly what they need to change).

2022-07-21 19:32 UTC, colearendt commented on package-manager/README.md
> +3. Outdated images will be removed periodically from DockerHub as product version updates are made. Please make plans to
Worth noting that GitHub .md syntax handles this numbering automatically (hence the all 1s, and it displays fine 😄 )

2022-07-21 19:32 UTC, colearendt commented on package-manager/README.md
> +1. This image is still underdevelopment and new versions may introduce **BREAKING** changes, read through the
I personally don't think we should make too much of connecting these two (under development and breaking changes). The breaking changes we have here are completely reversible with configuration, and we should have license to make BREAKING changes when it is for the good of our customers IMO 🤷 The TL; DR; is definitely "read the NEWS" 😄

2022-07-21 21:02 UTC, colearendt approved these changes
LGTM!

2022-07-21 22:49 UTC, merged