Dk/add jammy only
rstudio/rstudio-docker-products pull request #388
Opened 2022-08-30 20:27 UTC by dkasabovn

2022-08-31 03:26 UTC, dkasabovn commented
Looks like Snyk does not like checking the Azure-ml container

2022-09-06 15:51 UTC, melissa-barca approved these changes
LGTM!

2022-09-06 18:37 UTC, ianpittwood requested changes
lint.yaml needs to be updated and passed on the new files, but other than that LGTM.

2022-09-06 18:37 UTC, ianpittwood commented on .github/workflows/build-latest.yaml
> +          - {product: 'workbench', os: 'jammy'}
We should copy these changes to lint.yaml too before merging.

2022-09-07 15:31 UTC, ianpittwood approved these changes

2022-09-08 03:01 UTC, colearendt requested changes

2022-09-08 03:02 UTC, colearendt commented
We should also go about passing along the need for those other `jammy` builds for azureml, etc.

2022-09-08 17:47 UTC, ianpittwood commented on testutil.sh
> +just test-image $1 $(just get-version $1 --type=release --local) $IMAGES
Looks like they may have been Daniel's testing scripts? They're just wrapping existing `just` targets so let's remove them.

2022-09-08 17:49 UTC, ianpittwood commented on workbench/Dockerfile.jammy
> +    bash Miniconda3-4.7.12.1-Linux-x86_64.sh -bp /opt/python/${PYTHON_VERSION} && \
They'll have to be replaced across all our Dockerfiles anyways so I personally don't think its a big deal to leave it as is. Are we almost ready to use the source builds?

2022-09-08 17:50 UTC, ianpittwood commented on .github/workflows/build-latest.yaml
>        matrix:
Is jammy officially supported by all products? If so, I think it would be safe to add to both.

2022-09-08 17:57 UTC, ianpittwood commented on workbench/Dockerfile.jammy
> +    bash Miniconda3-4.7.12.1-Linux-x86_64.sh -bp /opt/python/${PYTHON_VERSION} && \
Looks like #370 will cover that update. I'm good waiting on implementing that.

2022-09-23 03:03 UTC, colearendt approved these changes
LGTM! My one remaining comment. As soon as we merge this, we will have these images up and accessible to customers. If we're going to go straight to building the `latest` images that are customer facing, it would be great if someone were "on deck" to run all of these images and ensure that some standard product workflows work with them. 

That could help us avoid the case that a customer tries to use the `jammy` image and open an issue or support thread when it doesn't work. (i.e. prevent a firefight 😄)

2022-10-13 19:14 UTC, merged