Update image READMEs and automatically update Docker Hub READMEs
rstudio/rstudio-docker-products pull request #433
Opened 2022-11-18 13:55 UTC by ianpittwood

2022-11-28 14:34 UTC, melissa-barca approved these changes
LGTM!

2022-11-28 15:41 UTC, colearendt requested changes
Still a few places where `latest` is sticking around in compose and elsewhere 🙈 We don't build those images anymore. Otherwise LGTM! Will be nice to have this connected w/ github

2022-11-28 15:41 UTC, colearendt commented on .github/workflows/update-readme.yaml
> +      - dev
Do we want to run this on the `dev` branch? That doesn't seem desirable to me

2022-11-28 15:41 UTC, colearendt commented on connect-content-init/README.md
> +* [`latest`, `2022.10.0`, `bionic`, `ubuntu1804`, `bionic-2022.10.0`, `ubuntu1804-2022.10.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/connect/Dockerfile.bionic)
```suggestion
* [`2022.10.0`, `bionic`, `ubuntu1804`, `bionic-2022.10.0`, `ubuntu1804-2022.10.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/connect/Dockerfile.bionic)
```

We do not build a `latest` anymore 😅

2022-11-28 15:41 UTC, colearendt commented on connect/README.md
> +   - Avoid using the `latest` tag to avoid unexpected issues, and
```suggestion
   - Avoid using the `latest` or `{operating-system}` tags to avoid unexpected version upgrades, and
```

2022-11-28 15:41 UTC, colearendt commented on connect/README.md
> +* [`latest`, `2022.11.0`, `bionic`, `ubuntu1804`, `bionic-2022.11.0`, `ubuntu1804-2022.11.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/connect/Dockerfile.bionic)
```suggestion
* [`2022.11.0`, `bionic`, `ubuntu1804`, `bionic-2022.11.0`, `ubuntu1804-2022.11.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/connect/Dockerfile.bionic)
```

2022-11-28 15:41 UTC, colearendt commented on package-manager/README.md
> +* [`latest`, `2022.11.0`, `bionic`, `ubuntu1804`, `bionic-2022.11.0`, `ubuntu1804-2022.11.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/Dockerfile.ubuntu1804)
```suggestion
* [`2022.11.0`, `bionic`, `ubuntu1804`, `bionic-2022.11.0`, `ubuntu1804-2022.11.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/Dockerfile.ubuntu1804)
```

2022-11-28 15:41 UTC, colearendt commented on package-manager/README.md
>     - Avoid using the `latest` tag to avoid unexpected issues, and
```suggestion
   - Avoid using the `latest` or `{operating-system}` tags to avoid unexpected version changes, and
```

2022-11-28 15:41 UTC, colearendt commented on r-session-complete/README.md
> +* [`latest`, `2022.07.2`, `bionic`, `ubuntu1804`, `bionic-2022.07.2`, `ubuntu1804-2022.07.2`](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/Dockerfile.ubuntu1804)
```suggestion
* [`2022.07.2`, `bionic`, `ubuntu1804`, `bionic-2022.07.2`, `ubuntu1804-2022.07.2`](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/Dockerfile.ubuntu1804)
```

2022-11-28 15:41 UTC, colearendt commented on r-session-complete/README.md
> +   - Avoid using the `latest` tag to avoid unexpected issues, and
```suggestion
   - Avoid using the `latest` or `{operating-system}` tags to avoid unexpected version changes, and
```

2022-11-28 15:41 UTC, colearendt commented on workbench/README.md
> +* [`latest`, `2022.07.2`, `bionic`, `ubuntu1804`, `bionic-2022.07.2`, `ubuntu1804-2022.07.2`](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/Dockerfile.ubuntu1804)
```suggestion
* [`2022.07.2`, `bionic`, `ubuntu1804`, `bionic-2022.07.2`, `ubuntu1804-2022.07.2`](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/Dockerfile.ubuntu1804)
```

2022-11-28 15:41 UTC, colearendt commented on workbench/README.md
> +   - Avoid using the `latest` tag to avoid unexpected issues, and
```suggestion
   - Avoid using the `latest` or `{operating-system}` tags to avoid unexpected version changes, and
```

2022-11-28 16:39 UTC, ianpittwood commented on .github/workflows/update-readme.yaml
> +      - dev
I think I originally included that with the intent to update the preview READMEs too. I eventually decided that wasn't much of a value add and must have forgot to drop dev. I'll remove that trigger unless we want to update the previews.

2022-12-05 16:37 UTC, ianpittwood commented
@colearendt everything should be updated from your suggestions!

2022-12-09 15:14 UTC, colearendt requested changes
Still a few things seem broken 😄

2022-12-09 15:14 UTC, colearendt commented on connect-content-init/README.md
> +* [`2022.10.0`, `bionic`, `ubuntu1804`, `bionic-2022.10.0`, `ubuntu1804-2022.10.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/connect/Dockerfile.bionic)
Are these getting programmatically updated by `Just`? They seem out of sync?

Also may want to pull latest from `main`? I think we're on 12.0 now?

2022-12-09 15:14 UTC, colearendt commented on connect/README.md
>      rstudio/rstudio-connect:latest
still missing some `latest` references?

2022-12-09 15:14 UTC, colearendt commented on connect/README.md
> +| `2022.11.0` | Default HTTP Port for RStudio Connect |
Looks like our regex has gone awry 😅 Maybe require something that has a `.`?

2022-12-09 15:14 UTC, colearendt commented on package-manager/README.md
> +* [`2022.11.0`, `bionic`, `ubuntu1804`, `bionic-2022.11.0`, `ubuntu1804-2022.11.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/package-manager/Dockerfile.ubuntu1804)
This is a bit out-of-date too

2022-12-09 15:14 UTC, colearendt commented on package-manager/README.md
> +| `2022.11.0` | Default HTTP Port for RStudio Package Manager |
Another regex anomaly

2022-12-09 15:14 UTC, colearendt commented on r-session-complete/README.md
> +* Where to get help: [our Github Issues page](https://github.com/rstudio/rstudio-docker-products/issues)
Missing reference to the image?

2022-12-09 15:14 UTC, colearendt commented on package-manager/README.md
> +* Where to get help: [our Github Issues page](https://github.com/rstudio/rstudio-docker-products/issues)
Missing reference to the image? Consistency w/ Connect

2022-12-09 15:14 UTC, colearendt commented on workbench/README.md
> +* Where to get help: [our Github Issues page](https://github.com/rstudio/rstudio-docker-products/issues)
Did you decide not to reference these on DockerHub / ghcr.io? If not, then maybe it makes sense to drop for Connect

2022-12-09 15:14 UTC, colearendt commented on workbench/README.md
> +| `RSW_TESTUSER_UID` | Test user UID | `2022.07.2` |
Another bad regex

2022-12-09 15:14 UTC, colearendt commented on workbench/README.md
> +| `2022.07.2` | Port for RStudio Launcher server |
More

2022-12-09 21:35 UTC, ianpittwood commented on connect-content-init/README.md
> +* [`2022.10.0`, `bionic`, `ubuntu1804`, `bionic-2022.10.0`, `ubuntu1804-2022.10.0`](https://github.com/rstudio/rstudio-docker-products/blob/main/connect/Dockerfile.bionic)
I think I started this PR before we were even on 11 so I'll rerun that :smile:

2022-12-12 18:00 UTC, ianpittwood commented on connect/README.md
> +| `2022.11.0` | Default HTTP Port for RStudio Connect |
`sed` was misbehaving so this is probably an artifact from me trying to get it to work correctly. These should be fixed now.

2022-12-12 18:03 UTC, ianpittwood commented on package-manager/README.md
> +* Where to get help: [our Github Issues page](https://github.com/rstudio/rstudio-docker-products/issues)
I only included the image link for the connect-content-init image so people could navigate back to that one. I can include it on every one though so it's easier for Github viewers.

2022-12-15 17:44 UTC, colearendt approved these changes
Looking great! Well done!

2022-12-15 17:44 UTC, colearendt commented on connect-content-init/README.md
> +just build ubuntu1804 1.8.8.3-dev236
No need for this to be up-to-date, but I could see an argument for moving this to at least a date-based version 😄 Or putting in a placeholder, etc.

2022-12-15 18:20 UTC, ianpittwood commented on connect-content-init/README.md
> +just build ubuntu1804 1.8.8.3-dev236
Good point, I updated it to at least be a date-based version so we don't confuse anyone!

2022-12-15 18:59 UTC, merged