bump RSW_VERSION to 2022.12.0+353.pro20
rstudio/rstudio-docker-products pull request #448
Opened 2022-12-19 23:56 UTC by skyeturriff

Bumps the release version for Workbench to 2022.12.0+353.pro20

It looks like there were some changes (file additions/deletions) since our last bump, so I just did a search for `RSW_VERSION` and changed it where ever it popped up

2022-12-19 23:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=448) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=448) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rstudio-docker-products?pullRequest=448) it.</sub>

2022-12-20 00:30 UTC, colearendt requested changes
Sorry, we have a bit more to do for this release. The dev branch has changes we need, and we have some other pending changes that are desirable to pull in at the same time. Hoping to take a deeper look tomorrow!

2022-12-20 15:15 UTC, skyeturriff commented
Got it! No problem, thanks @colearendt !

2022-12-20 21:09 UTC, colearendt approved these changes
LGTM! I changed the base branch to `dev` so we can finish things up there before merging to `main` 😄

2022-12-20 21:10 UTC, merged