Add file command for rsession-complete images
rstudio/rstudio-docker-products pull request #479
Opened 2023-02-17 20:56 UTC by jeffvroom

The rsession will try to run `file ...` when trying to open a file without a known suffix.  If that command gets an error, it reports the file as binary so we need this extra command.

2023-02-17 20:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=479) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=479) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rstudio-docker-products?pullRequest=479) it.</sub>

2023-02-17 22:15 UTC, melissa-barca approved these changes
LGTM

2023-03-14 18:48 UTC, ianpittwood approved these changes

2023-03-14 18:58 UTC, cm421 approved these changes
LGTM!

2023-03-14 20:49 UTC, ianpittwood requested changes
My bad, we missed one `\` here. Other than that I think it should be good pending the builds.

2023-03-14 20:49 UTC, ianpittwood commented on r-session-complete/Dockerfile.ubuntu2204
> +      file
```suggestion
      file \
```

2023-03-15 18:10 UTC, colearendt approved these changes
LGTM! Thanks @jeffvroom ! This is an interesting problem - have y'all thought about whether these types of dependencies should be declared explicitly (i.e. as a build / install dependency?). It's weird because it isn't a proper system dependency, but we do shell out to something that we depend on on the system 🤷‍♂️

2023-03-18 00:33 UTC, jeffvroom commented
@colearendt Thanks, that's a great suggestion. How about if I cancel this PR and fix this problem in:  https://github.com/rstudio/rstudio-pro/issues/4455?

2023-03-18 00:33 UTC, closed without merging