Add Workbench for Google Cloud Workstations image
rstudio/rstudio-docker-products pull request #564
Opened 2023-06-22 16:25 UTC by ianpittwood

Adds the image definition for the initial release of Workbench for Google Cloud Workstations

2023-06-29 14:14 UTC, bschwedler requested changes
Most of my comments are geared toward attempting to reduce the size of the image layers where possible.  

I may have missed some places where we can do this, especially if they were buried in a script.
Also, is there an R package cache we can remove after packages are installed like I suggested for `pip`?  I don't know as much about managing packages there.

Note: I did not do a thorough review of the configuration files

2023-07-06 15:06 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/.env
> +QUARTO_VERSION=1.3.324
Good idea. I believe I've condensed everything down to the `.env` file now. This won't match up with the other projects in the repo, but it's a good pattern to try out and see if we want to update the other projects to follow it.

2023-07-06 15:20 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/README.md
> +* [`jammy`, `ubuntu2204`, `jammy-2022.07.2`, `ubuntu2204-2022.07.2`](https://github.com/rstudio/rstudio-docker-products/blob/main/workbench/Dockerfile.ubuntu2204)
I'm actually going to remove most of this file and link to Google Cloud Workstations docs instead. Most of the information in here won't apply to Workstations as it would to the normal image (where it was copied from).

2023-07-06 15:21 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/README.md
> +    rstudio/rstudio-workbench:ubuntu1804
Same as above.

2023-07-06 19:37 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Dockerfile
> +COPY startup/* /startup/base/
I combined them into a single block and tested to make sure things still worked.

2023-07-06 19:41 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Justfile
> +    ${volume_opts[@]} \
Removed `-x` flag

2023-07-06 19:43 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
Yeah I'll grant that it doesn't do anything with the caches. It still cleans up unnecessary or broken packages that may otherwise land in the final container though so I'd like to leave it unless there's an advantage to copy-pasting it onto all the `apt` usages.

2023-07-10 14:20 UTC, bschwedler approved these changes

2023-07-12 17:43 UTC, ianpittwood commented
Setting as blocked by #583. The issue has been escalated to Google and we are awaiting their response.

2023-08-08 21:44 UTC, msarahan approved these changes
I think this is fine. I left some comments about things to talk about, but I don't think any immediate change is needed.

2023-08-08 21:44 UTC, msarahan commented on workbench-for-google-cloud-workstations/.env
> +PYTHON_VERSION_JUPYTER=3.10.12
This confused me, as I thought that it was a third installation of python. Why are we explicitly setting this? Why isn't it just always presumed to be installed at PYTHON_VERSION?

2023-08-08 21:44 UTC, msarahan commented on workbench-for-google-cloud-workstations/conf/repos.conf
> +CRAN=https://packagemanager.posit.co/cran/__linux__/focal/latest
It seems like we should be leaving this as the real CRAN URL, but making RSPM take priority. This is not especially a question about this PR, though, so perhaps it is best discussed elsewhere.

2023-08-08 21:44 UTC, msarahan commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +      apt-transport-https \
can these be moved to an external file in the deps folder, like we do for R and python packages?

2023-08-08 21:44 UTC, msarahan commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +    && apt-get update \
remove update since we did it above
```suggestion
```

2023-08-08 21:44 UTC, msarahan commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +    && apt-get update \
remove update since we did it above
```suggestion
```

2023-08-08 21:44 UTC, msarahan commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +RUN curl -O https://cdn.rstudio.com/r/ubuntu-2004/pkgs/r-${R_VERSION}_1_amd64.deb \
I wonder if it might be nicer to write a proper bash file here, and then use a loop for these duplicated lines. I'm ambivalent. It would be extra work. It would make the Dockerfile easier to read and update. It might make it easier to run/debug scripts outside of docker builds.

Up to you!

2023-08-08 21:44 UTC, msarahan commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +RUN /opt/python/"${PYTHON_VERSION_JUPYTER}"/bin/python -m venv /opt/python/jupyter \
A lot of this stuff has me feeling like we should have centralized scripts for this stuff. We must be duplicating a ton of this stuff between this and the other workstations image. I don't think it's important to consolidate it all here in this PR, but perhaps it is worth filing a tech debt ticket for.

2023-08-09 13:46 UTC, bschwedler requested changes

2023-08-09 13:46 UTC, bschwedler commented on workbench-for-google-cloud-workstations/TurboActivate.dat
Is this file the same as is present in the other directories?
I know that we need to have this as a file, not a symlink, in the docker build context.  Would it make sense to have a single file that can moved into the correct location before building the container?

Definitely out of scope for this PR though.

2023-08-09 13:46 UTC, bschwedler commented on workbench-for-google-cloud-workstations/conf/launcher-env
> +Environment: PATH=/opt/python/3.9.16/bin:$PATH
Do we still need this? This caused some issues on the DataOps platform, especially because it was pre-pended to the path. 

If we do, we need to update this to the appropriate patch version.

2023-08-09 13:46 UTC, bschwedler commented on workbench-for-google-cloud-workstations/docker-compose.test.yml
> +      # uses .env by default
❤️

2023-08-09 13:46 UTC, bschwedler commented on workbench-for-google-cloud-workstations/startup.sh
> +fi
Can we either wrap this section with `set +x` so we don't end up logging the license key?

2023-08-09 14:47 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/.env
> +PYTHON_VERSION_JUPYTER=3.10.12
This matches the pattern of the other Workbench products. I personally have no problem defaulting to one version or the other, but we should probably make it a global change for the repo.

2023-08-09 14:54 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +      apt-transport-https \
Yeah that would help slim down the Dockerfile itself, I'll do it. Perhaps we should apply this `deps/*` model to the other projects at some point.

2023-08-09 14:55 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +    && apt-get update \
I think we have to do it in each layer since we run `rm -rf /var/lib/apt/lists/*` to slim down at the end of each one.

2023-08-09 15:05 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/TurboActivate.dat
Though the files may seem identical, they are specific to each License Manager SKU. We can't share them across projects or things will a splode.

2023-08-09 15:08 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/conf/launcher-env
> +Environment: PATH=/opt/python/3.9.16/bin:$PATH
I have no clue! I noticed that these files tend to get wildly out of date in ever project that uses them. If we should keep it and update it, I'm happy to. If we can remove it, I would also be happy.

2023-08-09 15:09 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +    && apt-get update \
Same as above. I confirmed that we do need to do this each time if we remove the update lists at ever layer.

2023-08-09 15:32 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +RUN curl -O https://cdn.rstudio.com/r/ubuntu-2004/pkgs/r-${R_VERSION}_1_amd64.deb \
https://github.com/rstudio/rstudio-docker-products/issues/616

2023-08-09 15:32 UTC, ianpittwood commented on workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004
> +RUN /opt/python/"${PYTHON_VERSION_JUPYTER}"/bin/python -m venv /opt/python/jupyter \
https://github.com/rstudio/rstudio-docker-products/issues/616

2023-08-09 16:31 UTC, merged