Remove unused Workbench Components
rstudio/rstudio-docker-products pull request #624
Opened 2023-08-15 19:56 UTC by MariaSemple

This PR removes unused Workbench components to reduce the surface area for security vulnerabilities in the images. It also adds an "RStudio Pro session"-only image for certain use-cases.

2023-08-15 20:19 UTC, ianpittwood requested changes
Looks good so far. Just a few comments:
- We should update the `sed` targets in the root `Justfile` so versions get updated appropriately in the new `workbench-session-rstudio-pro` images.
- We should eventually add these builds into the workflows too. That should be as easy as adding in some more entries to the matrices.
- Is it possible we'll add more session images for Workbench? If so, it may be best to layer this in as a subdirectory like `workbench-session/rstudio-pro`.

2023-08-15 20:19 UTC, ianpittwood commented on shared/remove-workbench-extras.sh
> +rm /usr/lib/rstudio-server/bin/run-diagnostics
Should these also have `-f`?

2023-08-15 20:19 UTC, ianpittwood commented on workbench-session-rstudio-pro/remove-other-sessions.sh
> +rm /usr/lib/rstudio-server/bin/vscode-session-run
nit: no extra line

2023-08-15 20:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=624) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=624) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: colearendt<br/>:white_check_mark: ianpittwood<br/>:x: MariaSemple<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rstudio-docker-products?pullRequest=624) it.</sub>

2023-08-15 20:37 UTC, MariaSemple commented on shared/remove-workbench-extras.sh
> +rm /usr/lib/rstudio-server/bin/run-diagnostics
Happy to change it, but for some reason only the r-versions file had trouble

2023-08-15 20:46 UTC, msarahan approved these changes

2023-08-16 14:12 UTC, ianpittwood commented on shared/remove-workbench-extras.sh
> +rm /usr/lib/rstudio-server/bin/run-diagnostics
That's strange. Is it the only one present at the time this runs perhaps?

2023-08-16 19:19 UTC, MariaSemple commented on shared/remove-workbench-extras.sh
> +rm /usr/lib/rstudio-server/bin/run-diagnostics
No, I'm guessing is a permissions thing. The other ones are definitely present before this runs

2025-02-18 18:29 UTC, closed without merging