Update PPM to 2023.08.0-16
rstudio/rstudio-docker-products pull request #637
Opened 2023-09-12 17:11 UTC by nunyunuymi

2023-09-12 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=637) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rstudio-docker-products?pullRequest=637) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rstudio-docker-products?pullRequest=637) it.</sub>

2023-09-12 17:23 UTC, jonyoder approved these changes
Looks good to me, but let's see if someone on the Platform team can review, as well. I'm not too familiar with this repo after all the recent changes.

2023-09-12 17:25 UTC, jmwoliver commented on package-manager/Dockerfile.ubuntu1804
>  ARG RSPM_DOWNLOAD_URL=https://cdn.rstudio.com/package-manager/ubuntu/amd64
I had this in another PR, but I think we need to update the URLs on these Dockerfiles to be `/deb/` instead of `/ubuntu/` here and `/ubuntu22/` below. We can do it here and I'll close that PR if we want to.

https://github.com/rstudio/rstudio-docker-products/pull/635

2023-09-12 17:32 UTC, nunyunuymi commented on package-manager/Dockerfile.ubuntu1804
>  ARG RSPM_DOWNLOAD_URL=https://cdn.rstudio.com/package-manager/ubuntu/amd64
I pulled those changes into here

2023-09-12 17:33 UTC, jonyoder approved these changes

2023-09-13 15:06 UTC, ianpittwood requested changes
I'm seeing some missed version updates on my side:
* https://github.com/rstudio/rstudio-docker-products/blob/ppm-2023.08.0-16/package-manager/README.md?plain=1#L9-L10
* https://github.com/rstudio/rstudio-docker-products/blob/ppm-2023.08.0-16/docker-compose.yml#L47

Otherwise this LGTM. The failing build is for `r-session-complete` so it's unrelated to this upgrade.

2023-09-14 14:33 UTC, ianpittwood approved these changes
LGTM!

2023-09-14 14:33 UTC, merged