Update Pro Drivers to 2024.03.0
rstudio/rstudio-docker-products pull request #707
Opened 2024-03-14 14:35 UTC by bschwedler

Use the latest version of the Professional Drivers

2024-03-15 20:51 UTC, ianpittwood approved these changes

2024-03-15 20:52 UTC, ianpittwood requested changes
Is there a CentOS 7 release for this? I noticed those builds are failing for us.

2024-03-18 13:42 UTC, bschwedler commented
> Is there a CentOS 7 release for this? I noticed those builds are failing for us.
There is. The filename changed. I popped on a commit: `s/el7/el/`.

2024-03-19 14:00 UTC, ianpittwood approved these changes

2024-03-19 14:01 UTC, merged