Bump Connect to version 2024.03.0
rstudio/rstudio-docker-products pull request #713
Opened 2024-03-28 17:10 UTC by plascaray

This PR was created automatically by the Posit Connect release scripts.

2024-03-28 17:14 UTC, marcosnav approved these changes

2024-03-28 17:18 UTC, dbkegley approved these changes

2024-03-28 17:18 UTC, aronatkins requested changes
Update Quarto version before merge.

2024-03-28 17:49 UTC, aronatkins approved these changes
Updated products to use Quarto 1.4. Content images left using old Quarto versions. CC @dbkegley

2024-04-10 16:39 UTC, dbkegley commented
Closing this, we only need to merge these changes to main to do the release

2024-04-10 16:39 UTC, closed without merging