Bump r version to 4.4 to address CVE and alt version to 4.3.3
rstudio/rstudio-docker-products pull request #764
Opened 2024-05-08 19:33 UTC by GCRev

Hopefully these are all the correct occurrences.

2024-05-08 20:25 UTC, ianpittwood requested changes
We'll need to remove some of the changes in `docker-bake.hcl` to keep this isolated to Workbench. Other products will be handled separately.

2024-05-08 20:25 UTC, ianpittwood commented on docker-bake.hcl
> +            {os = "ubuntu2204", r_primary = "4.4.0", r_alternate = "4.3.3", py_primary = "3.12.1", py_alternate = "3.11.7"},
Only add one new build with the updated R and Python versions, please. Updating older builds will have unintended consequences for other products.

2024-05-08 20:25 UTC, ianpittwood commented on docker-bake.hcl
> +            {os = "ubuntu2204", r_primary = "4.4.0", r_alternate = "4.3.3", py_primary = "3.12.1", py_alternate = "3.11.7"},
I imagine PPM would be fine with this, but let's keep this PR focused on Workbench.

2024-05-08 20:25 UTC, ianpittwood commented on docker-bake.hcl
> +            {os = "ubuntu2204", r_primary = "4.4.0", r_alternate = "4.3.3", py_primary = "3.9.17", py_alternate = "3.8.17", quarto = DEFAULT_QUARTO_VERSION},
Please remove this. Connect should not have dependencies modified outside of a release.

2024-05-08 20:25 UTC, ianpittwood commented on docker-bake.preview.hcl
> +            {os = "ubuntu2204", r_primary = "4.4.0", r_alternate = "4.3.3", py_primary = "3.11.9", py_alternate = "3.10.14"},
This matrix is fine. The previews can be kept on the latest version since they're primarily for testing and internal use.

2024-05-08 20:25 UTC, ianpittwood commented on docker-bake.preview.hcl
>  }
Also should be fine to update these products exclusively for previews.

2024-05-08 20:25 UTC, ianpittwood commented on r-session-complete/Dockerfile.ubuntu2204
> +ARG R_VERSION_ALT=4.3.3
These variables could also get updated in the Workbench images, but I'll eventually remove the defaults because these get overwritten by `bake`.

2024-05-08 21:24 UTC, GCRev commented on docker-bake.hcl
> +            {os = "ubuntu2204", r_primary = "4.4.0", r_alternate = "4.3.3", py_primary = "3.12.1", py_alternate = "3.11.7"},
Sorry. I wasn't sure how this system works, so I just did a blanket replace.

2024-05-08 21:28 UTC, GCRev commented on r-session-complete/Dockerfile.ubuntu2204
> +ARG R_VERSION_ALT=4.3.3
Is changing the variables here necessary if the bake always overwrites them? Or should we keep this in?

2024-05-09 12:53 UTC, ianpittwood requested changes

2024-05-09 12:53 UTC, ianpittwood commented on r-session-complete/Dockerfile.ubuntu2204
> +ARG R_VERSION_ALT=4.3.3
It's not necessary, but the change isn't a problem either so I wouldn't ask you to go roll them back.

2024-05-09 12:53 UTC, ianpittwood commented on docker-bake.hcl
It looks like we lost the changes for Workbench in here, unless we're doing that separately when the 2024.04.1 patch is released.

2024-05-09 12:53 UTC, ianpittwood commented on docker-bake.preview.hcl
>              {os = "centos7", r_primary = "4.2.3", r_alternate = "4.1.3", py_primary = "3.11.9", py_alternate = "3.10.14"},
Remove this entry, please. We can make all the previews use the same dependency versions for their respective OSes.

2024-05-09 12:53 UTC, ianpittwood commented on docker-bake.preview.hcl
>              {os = "ubuntu2204", r_primary = "4.2.3", r_alternate = "4.1.3", py_primary = "3.11.9", py_alternate = "3.10.14"},
Same here, remove this and make all the downstream build matrices use the same R/Py dependency versions.

2024-05-09 17:17 UTC, ianpittwood approved these changes

2024-05-09 17:27 UTC, cm421 approved these changes
LGTM!

2024-05-09 18:42 UTC, merged