Bump PPM to 2024.04.2
rstudio/rstudio-docker-products pull request #787
Opened 2024-05-30 15:38 UTC by tylfin

2024-05-30 17:57 UTC, ianpittwood requested changes
Could you go ahead and upgrade to R 4.4.0 on your image as well?

2024-06-04 18:45 UTC, ianpittwood requested changes

2024-06-04 18:45 UTC, ianpittwood commented on package-manager/.env
> +R_VERSION=4.4.0
This will need to be changed in the docker-bake.hcl file instead. It's this line: https://github.com/rstudio/rstudio-docker-products/blob/dev/docker-bake.hcl#L113

Use these versions if you find them agreeable: https://github.com/rstudio/rstudio-docker-products/blob/dev/docker-bake.hcl#L101

2024-06-10 15:31 UTC, ianpittwood approved these changes
LGTM

2024-06-10 16:04 UTC, merged

2024-06-10 16:37 UTC, tylfin commented
Oh, can we revert this @ianpittwood it's not ready for release just yet

2024-06-10 16:38 UTC, ianpittwood commented
Sure, here's a revert: https://github.com/rstudio/rstudio-docker-products/pull/793

I reopened the branch too. Sorry about that. Could you keep it in draft mode in the future so I don't make that mistake again?